### PR TITLE
Use standard names for the output format

### PR DESCRIPTION
**Pull request by simleo**
Addresses #8 and #14. With these changes:

* Column headers in a biotracks data package are **always** the same, namely the ones defined in the `names.py` module
* The configuration file is now **optional**, since some input formats have a static layout where all values that need to be mapped to biotracks column headers are known in advance. When this is not the case, the TRACKING_DATA section can be used to specify which original field maps to each target biotracks field. The TOP_LEVEL_INFO section, if filled, is used to populate the top level of the data package's JSON descriptor. For data package compliance, only the "name" property is required, but we provide a default for that so the configuration file can be entirely optional.

This should enable #39 and validation.

### CODE REVIEW

**Comment by gsergeant** [comment]
Looks great. 👍  This will certainly be helpful for the CellMissy reader as well.

**Comment by sbesson** [comment]
Overall, looks good and simplifies readability, validation and maintenance. A couple of questions:

- is the `name` field in the configuration file effectively redundant or is it allowed to be have different values than `names.PACKAGE_NAME`?
- we are prefixing the package name with `cmso_` but suffixing the column names with `_cmso`. Worth discussing and unifying the behavior?
- once agreed upon, we might want to expand the Tracks specification to describe the data-package format and the set of standard names and associate them with a specification version

**Comment by simleo** [comment]
> is the name field in the configuration file effectively redundant or is it allowed to be have different values than names.PACKAGE_NAME?

The latter, i.e., it can be used to override the default `names.PACKAGE_NAME`. The `name` property is required in data packages, so we always provide a default if the script user does not specify one.

> we are prefixing the package name with cmso_ but suffixing the column names with _cmso. Worth discussing and unifying the behavior?

I think it's best to *prefix* them and certainly we have to unify them. I would not do it in this PR to avoid changing too many things at once.

> once agreed upon, we might want to expand the Tracks specification to describe the data-package format and the set of standard names and associate them with a specification version

Yes. We should have an API call that returns the specs version we are implementing (even frictionless does not have this yet, see https://github.com/frictionlessdata/datapackage-py/issues/149) and we should probably add that information to the data package's JSON descriptor as well (frictionless might also want to do this, in which case we can rely on their property).

**Comment by sbesson** [comment]
Follow-up steps can be discussed on Thursday esp. wrt naming. Merging this.

**Pull request merged**
