### PR TITLE
Reader for Mosaic files

### PR DESCRIPTION
**Pull request by gsergeant**
Added a reader for the Mosaic tracking plugin, as per issue #36 .
These files can be saved in multiple extension formats (csv, tsv, txt -- uses ImageJ Results tables), so I've changed the delegator for these cases. 

With pandas, the engine now auto-determines the separator and creates the correct reader class according to the first term in the header. This partially addresses #16 for now, at least for these three extensions.

Also fixes the minor indentation bug for #40

### CODE REVIEW

**Comment by simleo** [comment]
Travis build is broken. Frictionless moved to >= 1.0 versions of their packages and renamed `jsontableschema` to `tableschema`, but it looks like both are being installed and this ends up triggering an `ImportError`. I've tried simply changing the datapackage dep to `datapackage < 1.0` but it's not enough.

**Comment by agbeltran** [comment]
@gsergeant  could you please investigate why the build is failing? Please, assume the dependency is for ```datapackage < 1.0```. Thanks!

**Comment by gsergeant** [comment]
Ensuring the `datapackage` version seems to have worked. 

Excuse the seemingly extra re-commits, I essentially just rebased the branch.

**Comment by agbeltran** [comment]
Brilliant! I see that you added some documentation/examples, which is great. Have you also got some tests (sorry if I missed them)?

**Comment by gsergeant** [comment]
That I forgot, but will add it now.

**Review by agbeltran — APPROVED** [review]
I fixed a minor typo in the test and I think it is now good to go

**Pull request merged**
