### PR TITLE
pandas dataframe operations translated into numpy

### PR DESCRIPTION
**Pull request by pcmasuzzo**
Most of the `pandas `based operations have been replaced by `numpy `operations on arrays.
In the long term this is way more efficient for bigger data.

This PR addresses issue #33

### CODE REVIEW

**Comment by simleo** [comment]
Can you rebase away the spurious commits and force push? Thanks

**Comment by pcmasuzzo** [comment]
@simleo - done, can you confirm this worked pls?

**Comment by simleo** [comment]
Looks like it worked :)

**Comment by simleo** [comment]
The turning angles plot has changed. Is this expected? Showing for `ICY/example_1` here:

**Before:**

turning_angles

**After:**

turning_angles

**Review by simleo — APPROVED** [review]
Tested on `examples/ICY/example_1`, which should be the slowest IIRC.

Without this PR:

```
% time python3 create_dpkg.py ../examples/ICY/example_1/track_processor_ICY.xls
2017-06-26 15:44:05,971 INFO: [create_dpkg] Trying default config file location: "/Users/simleo/git/biotracks/examples/ICY/example_1/biotracks.ini"
2017-06-26 15:44:05,972 INFO: [IcyReader] IcyReader Reading "../examples/ICY/example_1/track_processor_ICY.xls"
2017-06-26 15:44:06,203 INFO: [create_dpkg] tabular files written to "dp"
2017-06-26 15:44:07,262 INFO: [create_dpkg] json file written to "dp"
2017-06-26 15:44:35,077 INFO: [create_dpkg] normalizing dataset to the origin of the coordinate system...
2017-06-26 15:44:55,663 INFO: [create_dpkg] computing turning angles...
python3 create_dpkg.py ../examples/ICY/example_1/track_processor_ICY.xls  57.29s user 0.47s system 99% cpu 57.846 total
```

With this PR:

```
% time python3 create_dpkg.py ../examples/ICY/example_1/track_processor_ICY.xls
2017-06-26 15:47:13,220 INFO: [create_dpkg] Trying default config file location: "/Users/simleo/git/biotracks/examples/ICY/example_1/biotracks.ini"
2017-06-26 15:47:13,221 INFO: [IcyReader] IcyReader Reading "../examples/ICY/example_1/track_processor_ICY.xls"
2017-06-26 15:47:13,466 INFO: [create_dpkg] tabular files written to "dp"
2017-06-26 15:47:14,530 INFO: [create_dpkg] json file written to "dp"
2017-06-26 15:47:34,520 INFO: [create_dpkg] normalizing dataset to the origin of the coordinate system...
2017-06-26 15:47:46,911 INFO: [create_dpkg] computing displacements in the two directions of motion...
2017-06-26 15:47:47,848 INFO: [create_dpkg] computing turning angles...
python3 create_dpkg.py ../examples/ICY/example_1/track_processor_ICY.xls  37.23s user 0.38s system 99% cpu 37.715 total
```

Results are the same except for turning angles, so waiting on confirmation that this is expected.

**Comment by pcmasuzzo** [comment]
This is expected, yes. Good for me to go.

**Pull request merged**
