### PR TITLE
Add version info

### PR DESCRIPTION
**Pull request by simleo**
Adds version info to the package. The `VERSION` file becomes the single point where the version string has to be changed, and now you can do:

```
>>> import dpkg
>>> dpkg.__version__
'0.1.1'
```

It also changes setup.py so that it does not dump the full license to the "License" PKG-INFO field.

### CODE REVIEW

**Comment by sbesson** [comment]
Overall :+1:. A couple of comments:

- there are many ways to single-sourcing the version (see https://packaging.python.org/single_source_version/#single-sourcing-the-version for a full discussion). In this case, the pre-release workflow is to bump the content of `VERSION` and leave the setup.py logic to handle the distribution creation is that correct?
- can you bump `VERSION` to 0.1.1?
- while reviewing the package metadata, thoughts about adding `classifiers` to `setup.py` (https://pypi.python.org/pypi?%3Aaction=list_classifiers)?

**Comment by simleo** [comment]
> In this case, the pre-release workflow is to bump the content of VERSION and leave the setup.py logic to handle the distribution creation is that correct?

Yes. I have added a `MANIFEST.in` that includes the `VERSION` file in the distribution, since it's required by `setup.py`.

I have also bumped the version and added some classifiers.

**Comment by sbesson** [comment]
:+1: Looks good to me. @pcmasuzzo @joshmoore @gsergeant any veto to merging this and releasing 0.1.1? I'll open an issue for the naming/distribution.

**Comment by pcmasuzzo** [comment]
OK for me to merge. 
I will comment on  #13 soon.

Thanks both.

**Pull request merged**
